#!/usr/bin/env bash

if [ -z "$CLONEFISH_GEN_HOME" ] ; then
    # try to find Clonefish
    if [ -d /opt/clonefish/generator ] ; then
        CLONEFISH_GEN_HOME=/opt/clonefish/generator
    fi

    if [ -d "${HOME}/opt/clonefish/generator" ] ; then
        CLONEFISH_GEN_HOME="${HOME}/opt/clonefish/generator"
    fi

    if [ -d "/usr/local/clonefish/generator" ] ; then
        CLONEFISH_GEN_HOME="/usr/local/clonefish/generator"
    fi

    if [ -d "${HOME}/usr/clonefish/generator" ] ; then
        CLONEFISH_GEN_HOME="${HOME}/usr/clonefish/generator"
    fi

    ## resolve links - the script name may be a link to phing's home
    SOURCE="${BASH_SOURCE[0]}"
    PRG="$( dirname "$SOURCE" )"
    while [ -h "$SOURCE" ]
    do
        SOURCE="$(readlink "$SOURCE")"
        [[ $SOURCE != /* ]] && SOURCE="$PRG/$SOURCE"
        PRG="$( cd -P "$( dirname "$SOURCE"  )" && pwd )"
    done
    PRG="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

    if [ -d "`dirname $PRG`" ] ; then
        CLONEFISH_GEN_HOME="`dirname $PRG`"
    fi

    export CLONEFISH_GEN_HOME
fi

if [ -f "$CLONEFISH_GEN_HOME/bin/phing.php" ] ; then
    export PHING_COMMAND="$CLONEFISH_GEN_HOME/bin/phing.php"
fi

if [ -z "$PHING_COMMAND" ] ; then
    export PHING_COMMAND="phing"
fi

if [ $# = 1 ] ; then
    $PHING_COMMAND -f "$CLONEFISH_GEN_HOME/build.xml" -Dusing.clonefish-gen=true -Dproject.dir=$saveddir $*
else
    $PHING_COMMAND -f "$CLONEFISH_GEN_HOME/build.xml" -Dusing.clonefish-gen=true -Dproject.dir=$*
fi
